In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

# 1. Python

**Task 1** (0.5 points)<br/> 
Enter numbers `a`,  `d` и `N`. Find sum of the first `N` members of arithmetic progression with the first member `a` and difference `d`, without using formula for the sum.

In [4]:
a = int(input())
d = int(input())
N = int(input())
sum = 0

for i in range(0, N):
    sum = sum + a
    a = a + d
print(sum)

1
3
5
35


**Task 2** (0.5 points) <br/> 
Enter a number `N`. Find sum of the first `N` memebers of harmonic series.

In [5]:
N = int(input())
sum = 0

for i in range(1, N+1):
    sum = sum + 1 / i
print(sum)

4
2.083333333333333


**Task 3** (0.5 points) <br/> 
Enter an integer number `N`. Check if it is a prime number.

In [13]:
def check_prime(n):
    for i in range(2, int(math.sqrt(n))+1):
        if n % i == 0:
            return False
    return True


N = int(input())
print(check_prime(N))

17
True


**Task 4** (0.5 points) <br/> 
Enter the first `N` prime numbers.

In [8]:
N = int(input())

for i in range(2, N+1):
    if i > 1:
        for j in range(2, i):
            if i % j == 0:
                break
        else:
            print(i)


20
2
3
5
7
11
13
17
19


**Task 5** (0.5 points) <br/> 
There are numbers: `a`, `b`, `c`. Without using functions `min`, `max` and other functions, find the maximum number.

In [10]:
a = int(input())
b = int(input())
c = int(input())

if a > b and a > c:
    print(a)
elif b > a and b > c:
    print(b)
elif c > a and c > b:
    print(c)

1
7
4
7


# 2. Numpy

**Task 1** (0.5 points) <br/>
Create two random arrays $a$ and $b$ with the same length. 

Calculate the following distances between the arrays:

* Euclidean Distance
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Manhattan Distance
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Cosine Distance
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$


In [ ]:
arr1 = np.random.rand(10)
print(arr1)
arr2 = np.random.rand(10)
print(arr2)

sum = 0
for i in range(0, 10):
    sum = sum + (arr1[i] - arr2[i]) ** 2
euclidean_dist = math.sqrt(sum)
print('Euclidean Distance: ', euclidean_dist)

manhattan_dist = 0
for i in range(0, 10):
    manhattan_dist = manhattan_dist + abs(arr1[i] - arr2[i])
print('Manhattan Distance: ', manhattan_dist)

#Cosine Distance - ?

**Task 2** (0.5 points) <br/>
Create a random array (`np.random.rand()`) with length of 10 and with sum of its elements equals to 2.

In [ ]:
arr = np.random.rand(10)
arr = arr / arr.sum() * 2
print(arr)

sum = 0
for i in range(0, 10):
    sum = sum + arr[i]
print('Sum of arr elements equals: ', sum)

**Task 3** (0.5 points) <br/>
Create a random array (`np.random.rand()`) with length of 100. Transform the array so, that 
* Maximum element(s) value is 1
* Minimum element(s) value is 0
* Other values are in interval 0-1 with keeping the order

In [3]:
arr = np.random.rand(100)
print(arr)

# Так функция и так возвращает значения от 0 до 1

[0.85245124 0.33509736 0.04822648 0.85393711 0.92685859 0.58905624
 0.23309229 0.80499718 0.50448001 0.48424036 0.96988259 0.70932984
 0.47223647 0.82054707 0.00352321 0.7671601  0.93547234 0.86631125
 0.69125651 0.71530629 0.10126913 0.5040106  0.19503508 0.85002792
 0.54639348 0.08662732 0.68758944 0.50354606 0.01303921 0.2122112
 0.74286969 0.49565444 0.00961195 0.97600022 0.13770728 0.59159732
 0.06772656 0.43824951 0.61501147 0.23423291 0.91098118 0.06665103
 0.47220007 0.52864094 0.63726853 0.85730404 0.59210096 0.93448004
 0.62696834 0.68081172 0.89278971 0.24257036 0.46893815 0.83577655
 0.9471588  0.94588491 0.80169103 0.50259483 0.3538237  0.53236823
 0.87501128 0.47926441 0.18682347 0.27867174 0.83627411 0.90325926
 0.95768994 0.06541733 0.1261005  0.17120541 0.2090243  0.85024187
 0.96296267 0.72025944 0.64539448 0.58297109 0.93541878 0.36093616
 0.7242926  0.72954965 0.4335918  0.13941351 0.66578948 0.03303347
 0.26935202 0.84302442 0.36856869 0.01763317 0.09411278 0.06709

**Task 4** (0.5 points) <br/>
Create a random array with length of 20 with integers from [0,50]. Select elements that are smaller than 5th percentile and larger than 95th percentile

In [ ]:
arr = np.random.randint(51, size = 20)
print(arr)

percentile = np.percentile(arr, 5)
print('5th percentile is: ', percentile)
for i in range(0, 20):
    if arr[i] < percentile:
        print(arr[i])
        
percentile = np.percentile(arr, 95)
print('95th percentile is: ', percentile)
for i in range(0, 20):
    if arr[i] > percentile:
        print(arr[i])

**Task 5** (0.5 points) <br/>
Create an array with shape of $5 \times 6$ with integer from [0,50]. Print a column that contains the maximum element of the array.

In [11]:
arr = np.random.randint(0, 51, (5, 6))
print(arr)
print('Maximum element of the array: ', arr.max())
for i in range(0, 5):
    for j in range(0, 6):
        if arr[i, j] == arr.max():
            print('Column: ', j)

[[ 0  9 12 43 27 21]
 [ 7 46 18 44 35 22]
 [46  9 34  5 33  7]
 [43 23  5 47 41 47]
 [15 27 22 40  1 13]]
Maximum element of the array:  47
Column:  3
Column:  5


**Task 6** (0.5 points) <br/>

Replace all missing values in the following array with mean.

In [24]:
arr = np.random.rand(10)
idx = np.random.randint(0, 10, 4)
arr[idx] = np.nan
arr

array([0.06462344,        nan,        nan, 0.50471296, 0.18644893,
       0.77996819, 0.84338688, 0.32531838,        nan,        nan])

In [28]:
avg = arr[~np.isnan(arr)].mean()

print(avg)
for i in range (0, 4):
    arr[idx[i]] = avg
arr

0.4507431288066728


array([0.06462344, 0.45074313, 0.45074313, 0.50471296, 0.18644893,
       0.77996819, 0.84338688, 0.32531838, 0.45074313, 0.45074313])

### Linear Regression

Download [file 1](https://www.dropbox.com/s/kg9px9v3xfysak9/tutorial_dataset.csv?dl=0) and [file 2](https://www.dropbox.com/s/f87gm612o144emx/tutorial_dataset_2.csv?dl=0) into a directory with this notebook. Using function `loadtxt` in `numpy` load data from the first file. Assign y = D[:,0] аnd X = D[:, 1:].


We will use one magic formula to find linear regression coefficients. You will prove this formula on your next lectures of the course.

Linear regression model in matrix form looks like: $\hat{y} = X\hat{\beta}$, where

$$ \hat{\beta} = (X^\top X)^{-1} X^\top y $$
Model residuals are calculated as
$$ \text{res} = y - \hat{y} $$


**Task 7** (2.5 points)<br/>
1. Load the data
2. Find parameters $\hat{\beta}$ using the formula above
3. Make a plot with the model residuals on Y axis and $\hat{y}$ on X axis

In [14]:
## load data
D = np.loadtxt('tutorial_dataset.csv', 
               skiprows=1, 
               delimiter=',')

## Your code here

# 3. Pandas

### Wine Quality

Download [sample](https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv) with information about wine characteristics and its quality.

In [15]:
## Your code here

**Task 1 ** (1 point) <br/>
* How much objects are in the sample?
* What features describe the objects? How much these features?
* What is feature a target variable?
* What are their ranges?
* Are there any missing values?

In [16]:
## Your code and answers here

**Task 2** (1 point)<br/>
What features affect the target variable the most?

In [17]:
## Your code here